# Generated by Django 4.2.7 on 2025-11-19 13:05

import django.core.validators
from django.db import migrations, models

import authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", authentication.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Prefer not to say", "Prefer not to say"),
                    ("Other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
