# Generated by Django 4.2.7 on 2025-11-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_managers_alter_user_age_alter_user_gender"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
