# Generated by Django 4.2.7 on 2025-12-12 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        18, message="Age must be at least 18."
                    ),
                    django.core.validators.MaxValueValidator(
                        120, message="Age must be at most 120."
                    ),
                ],
            ),
        ),
    ]
