# Generated by Django 4.2.7 on 2026-01-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_user_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="medical_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.DeleteModel(
            name="MedicalHistory",
        ),
    ]
