# Generated by Django 4.2.7 on 2025-11-19 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.TextField(
                        db_index=True,
                        help_text="Unique chat identifier used for vector search (created_at timestamp)",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Chat",
                        help_text="User-defined chat name, can be changed anytime",
                        max_length=255,
                    ),
                ),
                (
                    "patient_info",
                    models.TextField(
                        blank=True,
                        help_text="Patient information for this chat session (Age, Gender, Clinical Notes)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Chat creation timestamp, also used as chat_id for vector search",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "db_table": "chats",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text='Encrypted message content stored as JSON: {"prompt": "...", "response": "..."}'
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat_app.chat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("image", "Image"), ("pdf", "PDF")],
                        help_text="Type of file: image or pdf",
                        max_length=10,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="chat_app.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message File",
                "verbose_name_plural": "Message Files",
                "db_table": "message_files",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["message"], name="message_fil_message_872ad9_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "-created_at"], name="messages_chat_id_1405f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["user", "-created_at"], name="chats_user_id_e04d4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(fields=["chat_id"], name="chats_chat_id_c79054_idx"),
        ),
    ]
