# Generated by Django 4.2.7 on 2025-11-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="messages_chat_id_1405f3_idx",
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "created_at"], name="messages_chat_id_ec31ea_idx"
            ),
        ),
    ]
