# Generated by Django 4.2.7 on 2026-01-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0002_alter_message_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagefile",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="messagefile",
            name="file_type",
        ),
        migrations.AlterField(
            model_name="messagefile",
            name="file_name",
            field=models.CharField(
                help_text="Complete filename with extension (e.g., report.pdf, scan.jpeg)",
                max_length=255,
            ),
        ),
    ]
